### ISSUE TITLE
Uncaught TypeError: this._mutualExcluse is not a function

### ISSUE THREAD

**Issue by Flaminator89** [y-js/y-element#1]
I'm getting the following error when trying to follow the radio-button demo and things aren't being synced...

Uncaught TypeError: this._mutualExcluse is not a function (y-element.html:367)

HTML is per the demo:
```
<y-element connector-name="websockets-client" connector-room="room" db-name="memory">
	  	  <y-map name="elements" data="{{elements}}"></y-map>
</y-element>
Radio Buttons:
<paper-radio-group selected="{{elements.radio}}">
    <paper-radio-button name="cool">Cool</paper-radio-button>
    <paper-radio-button name="great">Great</paper-radio-button>
    <paper-radio-button name="awesome">Awesome!!</paper-radio-button>
</paper-radio-group>
```

Any idea what the issue might be?

**Comment by dmonad** [comment]
Unfortunately, I can't reproduce the problem. But I may have an idea why it might not work. I'm going to try that tomorrow. Are you, by any chance, using polymer 2? Haven't tested it with polymer 2 ..

**Comment by dmonad** [comment]
For some reason your application tries to change the data property. I made the data property read-only. v0.1.0 should fix the error message.

If the error still persists, could you send me your bower.json, including the versions of your dependencies? I'd also like to see the complete index.html. Just put it here

**Comment by Flaminator89** [comment]
Ok, I do not get that error anymore (once I refreshed... :p).  Things aren't syncing yet across the browser, but that error seems to have gone away.  I will see if I can figure out why things aren't syncing for me but this did seem to solve the issue.

**Comment by Flaminator89** [comment]
I will post my bower dep and index.html later today though in case it is useful.  The only other thing i have in there is a platinum-sw service worker element.  Thanks!!

**Comment by Flaminator89** [comment]
Here at the dependencies of my bower...


`  "dependencies": {
    "yjs": "^12.1.4",
    "y-memory": "^8.0.7",
    "y-webrtc": "^8.0.6",
    "y-array": "^10.0.6",
    "y-text": "^9.2.0",
    "y-indexeddb": "^8.1.9",
    "platinum-sw": "^1.3.0",
    "y-element": "^0.1.0",
    "y-richtext": "^9.0.8",
    "y-js": "*",
    "y-websockets-client": "^8.0.15",
    "y-map": "^10.0.4",
    "paper-radio-group": "^1.2.1",
    "paper-radio-button": "^1.3.1",
    "paper-input": "^1.1.22",
    "paper-slider": "^1.0.13",
    "paper-toggle-button": "^1.2.1",
    "iron-demo-helpers": "^1.2.5",
    "polymer": "^1.7.1"
  }`

My index.html is being served through express over the same port I'm running websockets-server...
`
var express = require('express');
var SocketIO = require('socket.io');
var app = express();

var port = process.env.PORT || 8080;
var forceSsl = require('force-ssl-heroku');
app.use(forceSsl);

app.use(express.static('public'));
app.use(express.static('src/views'));

const server = app.listen(port, function(err){
	  console.log("Express server running on port:" + port);
  });
`

Finally my actual html element is main.html and reads as follows:

`  
<!DOCTYPE html>
  <html>
    <head>
        <link rel="import" href="lib/platinum-sw/platinum-sw-register.html">
    	<link rel="import" href="lib/platinum-sw/platinum-sw-cache.html">
    	<link rel="import" href="lib/y-element/y-element.html">
    	<link rel="import" href="lib/paper-radio-group/paper-radio-group.html">
    	<link rel="import" href="lib/paper-radio-button/paper-radio-button.html">
    </head>
    <body>

    <platinum-sw-register skip-waiting 
                            clients-claim auto-register 
                            reload-on-install 
                            on-service-worker-installed="displayInstalledToast">
      <platinum-sw-cache default-cache-strategy="fastest"></platinum-sw-cache>
    </platinum-sw-register>

		<y-element connector-name="websockets-client" connector-room="room" db-name="memory">
	  	  <y-map name="elements" data="{{elements}}"></y-map>
		</y-element>

        Radio Buttons:
		<paper-radio-group selected="{{elements.radio}}">
  		  <paper-radio-button name="cool">Cool</paper-radio-button>
  		  <paper-radio-button name="great">Great</paper-radio-button>
  		  <paper-radio-button name="awesome">Awesome!!</paper-radio-button>
		</paper-radio-group>
    </body>
  </html>
`
Since updating to y-element '0.1.0', like mentioned earlier I'm not seeing that error message.  I'm not sure how it would have been getting called though.  One thing I did notice is that I don't seem to have a problem syncing across clients when using the non-polymer code... like y-text with a text box, but switching out with the polymer element seems to break the sync.  Anyways, I'll post back here when If I'm able to figure out the issue.  Thanks Kevin!

**Comment by dmonad** [comment]
The data-binding feature (e.g. `{{elements}}`) is a Polymer thing. It does not work in a pure html file. Data-binding must always happen in some kind of `<template ..>` environment. Try the following:

```HTML
<template is="dom-bind">
    <y-element connector-name="websockets-client" connector-room="room" db-name="memory">
        <y-map name="elements" data="{{elements}}"></y-map>
    </y-element>

    Radio Buttons:
    <paper-radio-group selected="{{elements.radio}}">
        <paper-radio-button name="cool">Cool</paper-radio-button>
        <paper-radio-button name="great">Great</paper-radio-button>
        <paper-radio-button name="awesome">Awesome!!</paper-radio-button>
    </paper-radio-group>
</template>
```

This got me once too ;)

**Comment by Flaminator89** [comment]
Ahh!  Thanks, that does make sense.  To make sure I don't make any more of those rookie mistakes I decided to just take the entire demo and paste it in... and strangely, still not syncing for me.  I suppose that must mean it's something to do with the setup of the y-websockets-server that I have then, which is strange because it works with the y-text demo... one step closer though!  Thanks again Kevin!

**Comment by Flaminator89** [comment]
Ok... I'm still confused (:/)... I've spun up two pages to test out with the same y-websockets server on the backend.  The first page https://whispering-ravine-36150.herokuapp.com/main.html, and the second https://whispering-ravine-36150.herokuapp.com/index.html.  The websockets server is working fine for the non-polymer one (main.html) but the logs are showing that nothing is checking in with the server on the index.html one which is a copy of of the demo code for y-element...  Is there something different about how the url gets parsed when using the polymer element?  Currently I'm trying connector-url="https://www...".

**Comment by dmonad** [comment]
When using y-element, you have to include all dependencies (i.e. `y-websockets-client.js`, `y-memory.js`, `y-richtext.js) as <script> tags (y-richtext is already loaded as a dependency). Yjs waits for the modules to be loaded. And since they are never loaded, no Yjs instance is created. Try adding the dependencies ;)

I'm actually very unhappy about this concept, because it is not very verbose. I'm currently maintaining this concept for backwards compatibility. In the next major release, you will get proper warnings.

**Comment by Flaminator89** [comment]
Alrighty, dependencies do make the difference!  Now everything is working perfectly...  thanks for the help!
